"""Add MatchGroup model and product match_group_id

Revision ID: 9b278a858d41
Revises: a1b2c3d4e5f6
Create Date: 2026-05-01 21:56:55.073836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b278a858d41'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_product_id'), 'coupons', ['product_id'], unique=False)
    op.drop_constraint('coupons_product_id_fkey', 'coupons', type_='foreignkey')
    op.create_foreign_key(None, 'coupons', 'products', ['product_id'], ['id'])
    op.add_column('products', sa.Column('match_group_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'match_groups', ['match_group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'match_group_id')
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.create_foreign_key('coupons_product_id_fkey', 'coupons', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_coupons_product_id'), table_name='coupons')
    op.drop_table('match_groups')
    # ### end Alembic commands ###
